# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    container_name: youdo_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    restart: always

